######################################################################
# environment and task
env_suite: robomimic
env: transport

# future action forecasts
action_dim: 14
horizon_steps: 8

# observation history
obs_dim: 59
cond_steps: 1
###################################################################

defaults:
  - _self_
hydra:
  run:
    dir: ${logdir}
_target_: agent.pretrain.train_shortcut_agent.TrainShortCutAgent
name: ${env}_pre_shortcut_mlp_ta${horizon_steps}_td${denoising_steps}
logdir: ${oc.env:REINFLOW_LOG_DIR}/robomimic/pretrain/${env}_pre_shortcut_mlp_ta${horizon_steps}_td${denoising_steps}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
train_dataset_path: ${oc.env:REINFLOW_DATA_DIR}/robomimic/${env}/train.npz
normalization_path: ${oc.env:REINFLOW_DATA_DIR}/robomimic/${env}/normalization.npz
denoising_steps: 20
batch_size: 256
seed: 42
device: cuda:0
###########################################################
test_in_mujoco: true
act_steps: ${horizon_steps}
robomimic_env_cfg_path: cfg/robomimic/env_meta/${env}.json
eval_env:
  n_envs: 50
  name: ${env}
  best_reward_threshold_for_success: 1
  max_episode_steps: 800
  n_steps: 400 # align with finetuning script train.n_steps
  save_video: false
  wrappers:
    robomimic_lowdim:
      normalization_path: ${normalization_path}
      low_dim_keys: ['robot0_eef_pos',
                    'robot0_eef_quat',
                    'robot0_gripper_qpos',
                    "robot1_eef_pos",
                    "robot1_eef_quat",
                    "robot1_gripper_qpos",
                    'object'] # same order of preprocessed observations
    multi_step:
      n_obs_steps: ${cond_steps}
      n_action_steps: ${act_steps}
      max_episode_steps: ${eval_env.max_episode_steps}
      reset_within_step: true
###########################################################

wandb:
  entity: ${oc.env:REINFLOW_WANDB_ENTITY}
  project: robomimic-${env}-pretrain
  run: ${now:%Y-%m-%d}_${now:%H-%M-%S}_${name}
  offline_mode: false

train:
  n_epochs: 3000
  batch_size: ${batch_size}
  learning_rate: 1e-4
  weight_decay: 1e-6
  lr_scheduler:
    first_cycle_steps: 3000
    warmup_steps: 100
    min_lr: 1e-5
  save_model_freq: 500  # 10
  test_freq: 250        # test in mujoco
model:
  _target_: model.flow.shortcutflow.ShortCutFlow
  network:
    _target_: model.flow.mlp_shortcut.ShortCutFlowMLP
    horizon_steps: ${horizon_steps}
    action_dim: ${action_dim}
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    td_emb_dim: 32
    mlp_dims: [1024, 1024, 1024]
    cond_mlp_dims: [32, 32]
    activation_type: ReLU
    out_activation_type: Identity
    use_layernorm: false
    residual_style: true
    embed_combination_type: 'add'
  device: ${device}
  horizon_steps: ${horizon_steps}
  action_dim: ${action_dim}
  act_min: -1
  act_max: 1 
  obs_dim: ${obs_dim}
  max_denoising_steps: ${denoising_steps}
  seed: ${seed}
  self_consistency_k: 0.25
  delta: 1e-5
  sample_t_type: uniform # beta, logitnormal
ema:
  decay: 0.995
train_dataset:
  _target_: agent.dataset.sequence.StitchedSequenceDataset
  dataset_path: ${train_dataset_path}
  horizon_steps: ${horizon_steps}
  cond_steps: ${cond_steps}
  device: ${device}