######################################################################
# environment and task
env_suite: robomimic
env: transport

# future action forecasts
action_dim: 14     # two robots
horizon_steps: 8   # larger for this task.

# observation history
obs_dim: 18  # proprioception only, two robots
cond_steps: 1
img_cond_steps: 1

# observation shape
shape_meta:
  obs:
    rgb:
      shape: [6, 96, 96]  # not counting img_cond_steps
    state:
      shape: [18]
  action: 
    shape: [14]
###################################################################

defaults:
  - _self_
hydra:
  run:
    dir: ${logdir}
_target_: agent.pretrain.train_shortcut_agent.TrainShortCutAgent
name: ${env}_pre_shortcut_mlp_img_ta${horizon_steps}_td${denoising_steps}
logdir: ${oc.env:REINFLOW_LOG_DIR}/robomimic/pretrain/${env}/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
train_dataset_path: ${oc.env:REINFLOW_DATA_DIR}/robomimic/${env}-img/train.npz

# 
denoising_steps: 20 #100   100 causes overflow problem...
batch_size: 256
seed: 42
device: cuda:3
test_in_mujoco: true
wandb:
  entity: ${oc.env:REINFLOW_WANDB_ENTITY}
  project: robomimic-${env}-pretrain
  run: ${now:%Y-%m-%d}_${now:%H-%M-%S}_${name}
  offline_mode: false

train:
  n_epochs: 2000
  batch_size: ${batch_size}
  learning_rate: 1e-4
  weight_decay: 1e-6
  lr_scheduler:
    first_cycle_steps: 2000
    warmup_steps: 100
    min_lr: 1e-5
  epoch_start_ema: 20
  update_ema_freq: 10
  save_model_freq: 250 #500
  log_freq: 25 #100

model:
  _target_: model.flow.shortcutflow.ShortCutFlow
  network:
    _target_: model.flow.mlp_shortcut.ShortCutFlowViT
    backbone:
      _target_: model.common.vit.VitEncoder
      obs_shape: ${shape_meta.obs.rgb.shape}
      num_channel: ${eval:'3 * ${img_cond_steps}'} # each image patch is history concatenated
      cfg:
        patch_size: 8
        depth: 1
        embed_dim: 128
        num_heads: 4
        embed_style: embed2
        embed_norm: 0
    action_dim: ${action_dim}
    horizon_steps: ${horizon_steps}
    prop_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    img_cond_steps: ${img_cond_steps}
    td_emb_dim: 32
    mlp_dims: [768, 768, 768]
    cond_mlp_dims: [96,48,32] # to accomodate twice the complexity brought by two arms, while not being too complex as the dataset still only contains 100 episodes. 
    residual_style: true
    num_img: 2
    augment: true
    spatial_emb: 128
    embed_combination_type: 'add'
  device: ${device}
  horizon_steps: ${horizon_steps}
  action_dim: ${action_dim}
  act_min: -1
  act_max: 1 
  obs_dim: ${obs_dim}
  max_denoising_steps: ${denoising_steps}
  seed: ${seed}
  self_consistency_k: 0.25
  delta: 1e-5
  sample_t_type: uniform # beta, logitnormal
ema:
  decay: 0.995
train_dataset:
  _target_: agent.dataset.sequence.StitchedSequenceDataset
  use_img: true
  dataset_path: ${train_dataset_path}
  horizon_steps: ${horizon_steps}
  max_n_episodes: -1 # maximum value is 100 by default 
  cond_steps: ${cond_steps}
  img_cond_steps: ${img_cond_steps}
  device: ${device}