_target_: agent.eval.eval_reflow_agent.EvalReFlowAgent
name: ant-medium-expert-v0_eval_reflow_mlp_ta4_td20
logdir: log/gym/eval/ant-medium-expert-v0_eval_reflow_mlp_ta4_td20/2025-04-26_15-07-05_42
base_policy_path: final_experiments_record/gym/pretrain/ant/reflow/2025-03-29_19-23-57_42/checkpoint/best_769.pt
normalization_path: data/gym/ant-medium-expert-v0/normalization.npz
seed: 42
device: cuda:2
env_name: ant-medium-expert-v0
obs_dim: 111
action_dim: 8
denoising_steps: 20
denoising_step_list:
- 1
- 2
- 4
- 8
- 16
- 32
- 64
- 128
- 256
cond_steps: 1
horizon_steps: 4
act_steps: 4
batch_size: 128
n_steps: 1000
render_num: 0
env:
  n_envs: 40
  name: ant-medium-expert-v0
  max_episode_steps: 1000
  reset_at_iteration: false
  save_video: false
  best_reward_threshold_for_success: 3
  wrappers:
    mujoco_locomotion_lowdim:
      normalization_path: data/gym/ant-medium-expert-v0/normalization.npz
    multi_step:
      n_obs_steps: 1
      n_action_steps: 4
      max_episode_steps: 1000
      reset_within_step: true
model:
  _target_: model.flow.reflow.ReFlow
  network:
    _target_: model.diffusion.mlp_diffusion.DiffusionMLP
    horizon_steps: 4
    action_dim: 8
    cond_dim: 111
    time_dim: 16
    mlp_dims:
    - 512
    - 512
    - 512
    activation_type: ReLU
    out_activation_type: Identity
    use_layernorm: false
    residual_style: true
  device: cuda:2
  horizon_steps: 4
  action_dim: 8
  act_min: -1
  act_max: 1
  obs_dim: 111
  max_denoising_steps: 20
  seed: 42
