_target_: agent.eval.eval_diffusion_agent.EvalDiffusionAgent
name: walker2d-medium-v2_eval_diffusion_mlp_ta4_td20
logdir: ${oc.env:REINFLOW_LOG_DIR}/gym/eval/walker2d-medium-v2_eval_diffusion_mlp_ta4_td20/2025-04-16_15-10-41_42
base_policy_path: log/gym/pretrain/walker2d-medium-v2_pre_diffusion_mlp_ta4_td20/2024-06-12_23-06-12/checkpoint/state_3000.pt
normalization_path: ${oc.env:REINFLOW_DATA_DIR}/gym/walker2d-medium-v2/normalization.npz
seed: 42
device: cuda:3
env_name: walker2d-medium-v2
obs_dim: 17
action_dim: 6
denoising_steps: 20
cond_steps: 1
horizon_steps: 4
act_steps: 4
batch_size: 128
n_steps: 500
render_num: 0
env:
  n_envs: 40
  name: walker2d-medium-v2
  max_episode_steps: 1000
  reset_at_iteration: false
  save_video: false
  best_reward_threshold_for_success: 3
  wrappers:
    mujoco_locomotion_lowdim:
      normalization_path: ${oc.env:REINFLOW_DATA_DIR}/gym/walker2d-medium-v2/normalization.npz
    multi_step:
      n_obs_steps: 1
      n_action_steps: 4
      max_episode_steps: 1000
      reset_within_step: true
model:
  _target_: model.diffusion.diffusion.DiffusionModel
  predict_epsilon: true
  denoised_clip_value: 1.0
  network_path: log/gym/pretrain/walker2d-medium-v2_pre_diffusion_mlp_ta4_td20/2024-06-12_23-06-12/checkpoint/state_3000.pt
  network:
    _target_: model.diffusion.mlp_diffusion.DiffusionMLP
    time_dim: 16
    mlp_dims:
    - 512
    - 512
    - 512
    activation_type: ReLU
    residual_style: true
    cond_dim: 17
    horizon_steps: 4
    action_dim: 6
  horizon_steps: 4
  obs_dim: 17
  action_dim: 6
  denoising_steps: 20
  device: cuda:3
