_target_: agent.eval.eval_shortcut_img_agent.EvalImgShortCutAgent
name: can_eval_shortcut_mlp_img_ta4_td20
logdir: log/robomimic/eval/can_eval_shortcut_mlp_img_ta4_td20/2025-04-26_10-20-38_42
base_policy_path: log/robomimic/pretrain/can/ShortCut/can_pre_shortcut_mlp_img_ta4_td20/2025-04-25_15-22-25_42/checkpoint/state_2000.pt
robomimic_env_cfg_path: cfg/robomimic/env_meta/can-img.json
normalization_path: data/robomimic/can-img/normalization.npz
seed: 42
device: cuda:7
env_name: can
obs_dim: 9
action_dim: 7
denoising_steps: 20
denoising_step_list:
- 1
- 2
- 4
- 8
- 16
- 32
- 64
cond_steps: 1
img_cond_steps: 1
horizon_steps: 4
act_steps: 4
n_steps: 300
render_num: 0
batch_size: 128
env:
  n_envs: 1
  name: can
  best_reward_threshold_for_success: 1
  max_episode_steps: 300
  save_video: false
  use_image_obs: true
  wrappers:
    robomimic_image:
      normalization_path: data/robomimic/can-img/normalization.npz
      low_dim_keys:
      - robot0_eef_pos
      - robot0_eef_quat
      - robot0_gripper_qpos
      image_keys:
      - robot0_eye_in_hand_image
      shape_meta:
        obs:
          rgb:
            shape:
            - 3
            - 96
            - 96
          state:
            shape:
            - 9
        action:
          shape:
          - 7
    multi_step:
      n_obs_steps: 1
      n_action_steps: 4
      max_episode_steps: 300
      reset_within_step: true
  render: true
shape_meta:
  obs:
    rgb:
      shape:
      - 3
      - 96
      - 96
    state:
      shape:
      - 9
  action:
    shape:
    - 7
model:
  _target_: model.flow.shortcutflow.ShortCutFlow
  network:
    _target_: model.flow.mlp_shortcut.ShortCutFlowViT
    backbone:
      _target_: model.common.vit.VitEncoder
      obs_shape:
      - 3
      - 96
      - 96
      num_channel: 3
      cfg:
        patch_size: 8
        depth: 1
        embed_dim: 128
        num_heads: 4
        embed_style: embed2
        embed_norm: 0
    action_dim: 7
    horizon_steps: 4
    prop_dim: 9
    img_cond_steps: 1
    td_emb_dim: 32
    mlp_dims:
    - 512
    - 512
    - 512
    cond_mlp_dims:
    - 64
    - 32
    residual_style: true
    num_img: 1
    augment: true
    spatial_emb: 128
    embed_combination_type: add
  device: cuda:7
  horizon_steps: 4
  action_dim: 7
  act_min: -1
  act_max: 1
  obs_dim: 9
  max_denoising_steps: 20
  seed: 42
  self_consistency_k: 0.25
  delta: 1.0e-05
  sample_t_type: uniform
