######################################################################
env_suite: gym
env: walker2d-medium-v2

# future action forecasts
action_dim: 6
horizon_steps: 4

# observation history
obs_dim: 17
cond_steps: 1
###################################################################
defaults:
  - _self_
hydra:
  run:
    dir: ${logdir}
_target_: agent.pretrain.train_diffusion_agent.TrainDiffusionAgent
name: ${env}_pre_diffusion_mlp_ta${horizon_steps}_td${denoising_steps}_seed${seed}
logdir: ${oc.env:REINFLOW_LOG_DIR}/gym/pretrain/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
train_dataset_path: ${oc.env:REINFLOW_DATA_DIR}/gym/${env}/train.npz
normalization_path: ${oc.env:REINFLOW_DATA_DIR}/gym/${env}/normalization.npz
use_d4rl_dataset: True
test_in_mujoco: True
seed: 42
device: cuda:7
sim_device: cuda:0
denoising_steps: 20
batch_size: 128
train:
  n_epochs: 60            #3000, 1500
  batch_size: ${batch_size}
  learning_rate: 1e-3
  weight_decay: 1e-6
  lr_scheduler:
    first_cycle_steps: 3000 # 200
    warmup_steps: 1
    min_lr: 1e-4
  save_model_freq: 100
  test_freq: 100
wandb:
  entity: ${oc.env:REINFLOW_WANDB_ENTITY}
  project: gym-${env}-pretrain
  run: ${now:%H-%M-%S}_${name}
model:
  _target_: model.diffusion.diffusion.DiffusionModel
  predict_epsilon: True
  denoised_clip_value: 1.0
  network:
    _target_: model.diffusion.mlp_diffusion.DiffusionMLP
    horizon_steps: ${horizon_steps}
    action_dim: ${action_dim}
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    time_dim: 16
    mlp_dims: [512, 512, 512]
    activation_type: ReLU
    out_activation_type: Identity
    use_layernorm: False
    residual_style: True
  horizon_steps: ${horizon_steps}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  denoising_steps: ${denoising_steps}
  device: ${device}
ema:
  decay: 0.995
train_dataset:
  _target_: agent.dataset.sequence.StitchedSequenceDataset
  dataset_path: ${train_dataset_path}
  horizon_steps: ${horizon_steps}
  cond_steps: ${cond_steps}
  device: ${device}
  max_n_episodes: -1