#####################################
env_suite: robomimic
env_name: transport

obs_dim: 59
cond_steps: 1

action_dim: 14
horizon_steps: 8
act_steps: 8
#####################################

defaults:
  - _self_
hydra:
  run:
    dir: ${logdir}
_target_: agent.finetune.reinflow.train_ppo_shortcut_agent.TrainPPOShortCutAgent
name: ${env_name}_ft_shortcut_mlp_ta${horizon_steps}_td${denoising_steps}_tdf${ft_denoising_steps}_seed${seed}
logdir: ${oc.env:REINFLOW_LOG_DIR}/robomimic/finetune/${env_name}_ft_shortcut_mlp_ta${horizon_steps}_td${denoising_steps}_tdf${ft_denoising_steps}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
base_policy_path: ${oc.env:REINFLOW_LOG_DIR}/robomimic/pretrain/transport/ShortCut-state/state_1000.pt
robomimic_env_cfg_path: cfg/robomimic/env_meta/${env_name}.json
normalization_path: ${oc.env:REINFLOW_DATA_DIR}/robomimic/${env_name}/normalization.npz
resume_path: null
seed: 42
device: cuda:0
sim_device: cuda:0
test_in_mujoco: true
#####################################
denoising_steps: 4
ft_denoising_steps: 4
min_std: 0.05
max_std: 0.12
#####################################

eval_env:
  n_envs: 50
  name: ${env_name}
  best_reward_threshold_for_success: 1
  max_episode_steps: 800
  save_video: false
  wrappers:
    robomimic_lowdim:
      normalization_path: ${normalization_path}
      low_dim_keys:
      - robot0_eef_pos
      - robot0_eef_quat
      - robot0_gripper_qpos
      - robot1_eef_pos
      - robot1_eef_quat
      - robot1_gripper_qpos
      - object
    multi_step:
      n_obs_steps: ${cond_steps}
      n_action_steps: ${act_steps}
      max_episode_steps: ${env.max_episode_steps}
      reset_within_step: true
wandb:
  entity: ${oc.env:REINFLOW_WANDB_ENTITY}
  project: robomimic-${env_name}-finetune
  run: ${now:%Y-%m-%d}_${now:%H-%M-%S}_${name}
  offline_mode: false
train:
  n_train_itr: 201
  n_critic_warmup_itr: 2
  n_steps: 400
  gamma: 0.999
  actor_lr: 4.5e-5
  actor_weight_decay: 0
  actor_lr_scheduler:
    type: cosine
    first_cycle_steps: 100
    warmup_steps: 10
    min_lr: 2.0e-5
  critic_lr: 6.5e-4
  critic_weight_decay: 1.0e-05
  critic_lr_scheduler:
    type: cosine
    first_cycle_steps: 100
    warmup_steps: 10
    min_lr: 3e-4
  save_model_freq: 100
  val_freq: 10
  render:
    freq: 1
    num: 0
  reward_scale_running: true
  reward_scale_const: 1.0
  gae_lambda: 0.95
  batch_size: 10000
  update_epochs: 5
  vf_coef: 0.5
  ent_coef: 0.00 # 0.01
  target_kl: 0.01
  lr_schedule: fixed
  repeat_samples: true
  verbose: false
  clip_intermediate_actions: true
  account_for_initial_stochasticity: true
  max_noise_hold_ratio: 0.35
  max_noise_decay_ratio: 0.7
model:
  _target_: model.flow.ft_ppo.pposhortcut.PPOShortCut
  device: ${device}
  policy:
    _target_: model.flow.mlp_shortcut.ShortCutFlowMLP
    horizon_steps: ${horizon_steps}
    action_dim: ${action_dim}
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    td_emb_dim: 32
    mlp_dims: [1024, 1024, 1024]
    cond_mlp_dims: [32, 32]
    activation_type: ReLU
    out_activation_type: Identity
    use_layernorm: false
    residual_style: true
    embed_combination_type: 'add'
  critic:
    _target_: model.common.critic.CriticObs
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    mlp_dims: [256, 256, 256]
    activation_type: Mish
    residual_style: true
  actor_policy_path: ${base_policy_path}
  act_dim: ${action_dim}
  horizon_steps: ${horizon_steps}
  act_min: -1
  act_max: 1
  obs_dim: ${obs_dim}
  cond_steps: ${cond_steps}
  noise_scheduler_type: learn_decay
  inference_steps: ${denoising_steps}
  ft_denoising_steps: ${ft_denoising_steps}
  randn_clip_value: 3
  min_sampling_denoising_std: ${min_std}
  min_logprob_denoising_std: ${min_std}
  max_logprob_denoising_std: ${max_std}
  logprob_min: -1.0
  logprob_max: 1.0
  clip_ploss_coef: 0.01
  clip_ploss_coef_base: 0.01
  clip_ploss_coef_rate: 3
  clip_vloss_coef: null
  denoised_clip_value: 1.0
  time_dim_explore: 0
  learn_explore_time_embedding: false
  use_time_independent_noise: false
  noise_hidden_dims: [128,128]
  logprob_debug_sample: false
  logprob_debug_recalculate: false
  explore_net_activation_type: Tanh