env_name: halfcheetah-medium-v2
action_dim: 6
horizon_steps: 4
act_steps: 4
obs_dim: 17
cond_steps: 1
_target_: agent.eval.eval_shortcut_agent.EvalShortCutAgent
name: halfcheetah-medium-v2_eval_shortcut_mlp_ta4_td4
logdir: log/gym/eval/halfcheetah-medium-v2_eval_shortcut_mlp_ta4_td4/2025-04-29_21-43-47_42
base_policy_path: log/gym/pretrain/halfcheetah-v2/ShortCut/2025-04-25_08-57-33_42_state_40.pt
normalization_path: data/gym/halfcheetah-medium-v2/normalization.npz
seed: 42
device: cuda:3
denoising_steps: 4
denoising_step_list:
- 4
n_steps: 500
render_num: 0
env:
  n_envs: 40
  name: halfcheetah-medium-v2
  max_episode_steps: 1000
  reset_at_iteration: false
  save_video: false
  best_reward_threshold_for_success: 3
  wrappers:
    mujoco_locomotion_lowdim:
      normalization_path: data/gym/halfcheetah-medium-v2/normalization.npz
    multi_step:
      n_obs_steps: 1
      n_action_steps: 4
      max_episode_steps: 1000
      reset_within_step: true
model:
  _target_: model.flow.shortcutflow.ShortCutFlow
  network:
    _target_: model.flow.mlp_shortcut.ShortCutFlowMLP
    horizon_steps: 4
    action_dim: 6
    cond_dim: 17
    td_emb_dim: 16
    mlp_dims:
    - 512
    - 512
    - 512
    cond_mlp_dims:
    - 64
    - 16
    activation_type: ReLU
    out_activation_type: Identity
    use_layernorm: false
    residual_style: true
    embed_combination_type: add
  device: cuda:3
  horizon_steps: 4
  action_dim: 6
  act_min: -1
  act_max: 1
  obs_dim: 17
  max_denoising_steps: 4
  seed: 42
  self_consistency_k: 0.25
  delta: 1.0e-05
  sample_t_type: uniform
